Improve documentation language
TheUnderscores/Shoraldele pull request #23
Opened 2017-05-23 03:45 UTC by strugee

2017-05-23 03:47 UTC, shelvacu requested changes

2017-05-23 03:47 UTC, shelvacu commented on README.md
> +ProTip™: Don't
Only registered trademarks are accepted.

2017-05-23 03:48 UTC, strugee commented on README.md
> +ProTip™: Don't
@shelvacu this project is a disgrace, how dare you not merge my feature!!!!!!!!!1!!!1!!!!! I will be forking ASAP

You suck

2017-05-23 03:50 UTC, RobertCochran commented on README.md
> +ProTip™: Don't
:'(

2017-05-23 03:52 UTC, shelvacu commented on README.md
> +ProTip™: Don't
fork you too @strugee

2017-10-07 21:05 UTC, Riven-Spell approved these changes

2017-10-08 03:04 UTC, merged

2017-10-08 03:04 UTC, shelvacu commented
Whoops, my finger slipped. Twice.

2017-10-08 04:05 UTC, strugee commented
Victory™